import type { Tool } from '@/types'

export const tools: Tool[] = [
  {
    id: 'quick-note',
    name: '光速筆記',
    subtitle: '語音速記 → AI 分析',
    icon: 'pen-line',
    category: 'work',
    type: 'builtin',
    route: '/tools/quick-note',
    requiredKeys: ['CLAUDE_API_KEY'],
    status: 'active',
  },
  {
    id: 'tts',
    name: '出言不遜',
    subtitle: '腳本 → 語音',
    icon: 'mic',
    category: 'knowledge',
    type: 'builtin',
    route: '/tools/tts',
    requiredKeys: ['FISH_AUDIO_API_KEY', 'FISH_AUDIO_VOICE_ID', 'ELEVENLABS_API_KEY', 'ELEVENLABS_VOICE_ID'],
    status: 'active',
  },
  {
    id: 'storyboard',
    name: '麥麥分鏡',
    subtitle: '口白 → AI 分鏡圖',
    icon: 'clapperboard',
    category: 'knowledge',
    type: 'builtin',
    route: '/tools/storyboard',
    requiredKeys: ['GOOGLE_AI_API_KEY'],
    status: 'active',
  },
  {
    id: 'podcast-script',
    name: '腳本魔法師',
    subtitle: '知識 → TTS 腳本',
    icon: 'scroll-text',
    category: 'knowledge',
    type: 'builtin',
    route: '/tools/podcast-script',
    requiredKeys: ['CLAUDE_API_KEY'],
    status: 'active',
  },
  {
    id: 'email-scan',
    name: 'Email 掃描',
    subtitle: '每日信箱摘要',
    icon: 'mail-search',
    category: 'work',
    type: 'builtin',
    route: '/tools/email-scan',
    requiredKeys: ['GMAIL_API_KEY', 'CLAUDE_API_KEY'],
    status: 'active',
  },
  {
    id: 'invoice',
    name: '發票整理',
    subtitle: '分類匯出 PDF',
    icon: 'receipt',
    category: 'work',
    type: 'builtin',
    route: '/tools/invoice',
    requiredKeys: ['CLAUDE_API_KEY'],
    status: 'active',
  },
  {
    id: 'knowledge-thief',
    name: '知識小偷',
    subtitle: '影片字幕批次萃取',
    icon: 'graduation-cap',
    category: 'knowledge',
    type: 'external',
    externalUrl: '',
    status: 'active',
  },
  {
    id: 'dream-rec',
    name: '夢境記錄器',
    subtitle: '語音記夢 → AI 分析',
    icon: 'moon-star',
    category: 'personal',
    type: 'external',
    externalUrl: '',
    status: 'active',
  },
  {
    id: 'sinus-note',
    name: 'Sinus Note',
    subtitle: '香材配方管理',
    icon: 'wind',
    category: 'personal',
    type: 'external',
    externalUrl: '',
    status: 'active',
  },
  {
    id: 'bioforge',
    name: 'BioForge',
    subtitle: '健康追蹤（重建中）',
    icon: 'heart-pulse',
    category: 'health',
    type: 'external',
    externalUrl: '',
    status: 'coming-soon',
  },
]
